stages:
  # debug:
  #   cmd: python src/stages/python.py
  data_load:
    cmd: python src/stages/data_load.py
    outs:
      - data/zip
  data_process:
    cmd: python src/stages/data_process.py
    deps:
      - src/stages/data_process.py
      - src/utils/data_process.py
      - data/zip/
    outs:
      - data/processed/train_processed.zip
      - data/processed/test_processed.zip
  unpack:
    cmd: python src/stages/data_unpack.py
    deps:
      - data/processed/train_processed.zip
      - data/processed/test_processed.zip
    outs:
      - data/processed/train_processed:
          cache: false
      - data/processed/test_processed:
          cache: false
  train:
    cmd: python src/stages/train.py
    params:
      - train.number_images
      - train.nn
      - train.epochs
      - train.lr
      - train.fine_tune
    deps:
      - src/stages/train.py
      - src/train/models.py
      - data/processed/train_processed
      - data/processed/test_processed
    outs:
      - models/model.pkl
      - results/results.csv:
          cache: false
      - results/results.png:
          cache: false
  evaluate:
    cmd: python src/stages/evaluate.py
    deps:
      - results/results.csv
      - results/results.png
    outs:
      - results/test_results.json:
          cache: false
  train_to_predict:
    cmd: python src/stages/train_to_predict.py
    deps:
      - src/stages/train_to_predict.py
      - data/processed/train_processed
      - data/processed/test_processed
    outs:
      - models/model_predict.pkl
      - results/train_predict_results.csv:
          cache: false
  predict:
    cmd: python src/stages/predict.py
    deps:
      - src/stages/predict.py
      - models/model_predict.pkl
    outs:
      - predict/predict.csv:
          cache: false
metrics:
  - results/test_results.json
plots:
  - epoch vs loss:
      template: linear
      x: epoch
      y:
        results\results.csv:
          - train_loss
          - test_loss
      x_label: epoch
      y_label: loss
  - epoch vs accuracy:
      template: linear
      x: epoch
      y:
        results\results.csv:
          - train_acc
          - test_acc
      x_label: epoch
      y_label: accuracy
  - results\results.png
