stages:
  # debug:
  #   cmd: python src/stages/python.py
  data_load:
    cmd: python src/stages/data_load.py
    deps:
      - src/stages/data_load.py
  data_process:
    cmd: python src/stages/data_process.py
    deps:
      - src/stages/data_process.py
      - src/utils/data_process.py
    outs:
      - data/processed/:
          cache: false

  train:
    cmd: python src/stages/train.py
    params:
      - train.number_images
      - train.nn
      - train.epochs
      - train.lr
    deps:
      # - data/prepared
      - src/stages/train.py
    outs:
      - models/model.pkl
      - results/results.csv:
          cache: false
      - results/results.png:
          cache: false
plots:
  - epoch vs loss:
      template: linear
      x: epoch
      y:
        results\results.csv:
          - train_loss
          - test_loss
      x_label: epoch
      y_label: loss
  - epoch vs accuracy:
      template: linear
      x: epoch
      y:
        results\results.csv:
          - train_acc
          - test_acc
      x_label: epoch
      y_label: accuracy
  - results\results.png
