base:
  seed: 42
  log_level: INFO
  num_classes: 2
  num_pool: 4

data:
  root: "D:/data//bio02"
  train_link: "https://disk.yandex.ru/d/IUUTPJFOfwn_OQ"
  test_link: "https://disk.yandex.ru/d/K8Z-gQbspmxkhw"
  # train.zip -> ttrain_mels

  # RAW ZIP
  zip_folder: "data/zip"
  train_zip: "data/zip/train.zip"
  test_zip: "data/zip/test.zip"
  zip_label_name: "train/targets.tsv"
  train_target: "data/labels/targets.tsv"

  # PROCESSED ZIP
  processed_dir: "data/processed"
  processed_train_dir: "data/processed/train_processed"
  processed_test_dir: "data/processed/test_processed"
  processed_train_zip: "data/processed/train_processed.zip"
  processed_test_zip: "data/processed/test_processed.zip"

  # UNPACKED
  train_col_name: "name"
  train_col_label: "label"

train:
  number_images: 100
  nn_type:
  nn: resnet34 #[resnet18, resnet34, resnet50, resnet101, resnet152]
  weights: DEFAULT # IMAGENET1K_V1, DEFAULT
  epochs: 5
  lr: 0.00005
  fine_tune: false

  model: models/model.pkl
results:
  train_results_csv: results/results.csv
  train_results_png: results/results.png
